version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mariadb-banco
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mariadb-banco:
    container_name: banco
    build:
      context: ./db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cadastro
    volumes:
      - ./data:/var/lib/mysql
